services:
    redis:
        image: redis:alpine
        command: [ redis-server, --maxmemory 128mb, --maxmemory-policy volatile-lru, --save "" ]

    db:
        image: mariadb:10.7
        working_dir: /application
        command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb-file-per-table=1]
        volumes:
            - pimcore-database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=ROOT
            - MYSQL_DATABASE=pimcore
            - MYSQL_USER=pimcore
            - MYSQL_PASSWORD=pimcore

    nginx:
        image: nginx:stable-alpine
        ports:
            - 80:80
        volumes:
            - .:/var/www:ro
            - ./.docker/dev/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php-fpm
            - php-fpm-debug

    php-fpm:
        user: "${UID}:${GID}"
        build:
            context: .docker/dev/
            dockerfile: php.Dockerfile
            args:
                UID: "${UID}"
                GID: "${GID}"
        environment:
            COMPOSER_HOME: /var/www
        depends_on:
            - db
        volumes:
            - .:/var/www:cached
            - ./.docker/dev/custom.ini:/usr/local/etc/php/conf.d/custom.ini

    php-fpm-debug:
        build:
            context: .docker/dev/
            dockerfile: php.Dockerfile.debug
            args:
                UID: "${UID}"
                GID: "${GID}"
                LOCAL_IP: "${LOCAL_IP}"
        user: "${UID}:${GID}"
        depends_on:
            - db
        volumes:
            - .:/var/www:cached
            - ./.docker/dev/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        environment:
            PHP_IDE_CONFIG: serverName=localhost
            COMPOSER_HOME: /var/www

    supervisord:
        build:
            context: .docker/dev/
            dockerfile: supervisord.Dockerfile
            args:
                UID: "${UID}"
                GID: "${GID}"
        user: "${UID}:${GID}"
        depends_on:
            - db
        volumes:
            - .:/var/www:cached
            - ./.docker/dev/custom.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./.docker/dev/supervisord.conf:/etc/supervisor/conf.d/pimcore.conf:ro


volumes:
    pimcore-database:
